name: dart_wasm_test
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  web: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.12
  build_web_compilers: ^4.0.11
  lints: ^3.0.0
